### ISSUE TITLE
Camera issue 

### ISSUE THREAD

**Issue by DC4114** [ousli/Huawei-Matebook-D15-2020-Hackintosh#1]
Hi, Does your camera work? can you provide the model. can you provide the model id from system information app.

**Comment by ousli** [comment]
Hi,
Yes, the camera works, but I find the quality to be worse than on Windows.
Here is a screenshot if it can help you.
![image](https://user-images.githubusercontent.com/66948132/211632674-594ab077-7e8a-40d2-b5d6-caf991f8230d.png)

**Comment by DC4114** [comment]
I meant the system information app in macOS. I Have no idea why the camera doesn't work, i mapped everything correctly.

**Comment by ousli** [comment]
![image](https://user-images.githubusercontent.com/66948132/211750521-1983ce55-2895-4464-955f-344637126ad4.png)
I hope it can help you. For me the camera always work, so idk

**Comment by DC4114** [comment]
Thank you.
